-- =====================================================
-- EGO - xTablas (eliminar tablas)
-- Oracle SQL Developer
-- =====================================================

 
DROP TABLE RESEÑAS CASCADE CONSTRAINTS;
DROP TABLE Calificaciones CASCADE CONSTRAINTS;
DROP TABLE LISTA_CONTENIDO CASCADE CONSTRAINTS;
DROP TABLE LISTA_PENDIENTE CASCADE CONSTRAINTS;
DROP TABLE LISTA CASCADE CONSTRAINTS;
DROP TABLE ETIQUETAS CASCADE CONSTRAINTS;
DROP TABLE PERSONAL_CONTENIDO CASCADE CONSTRAINTS;
DROP TABLE PERSONAL_ROL CASCADE CONSTRAINTS;
DROP TABLE PERSONAL CASCADE CONSTRAINTS;
DROP TABLE SERIE CASCADE CONSTRAINTS;
DROP TABLE PELICULA CASCADE CONSTRAINTS;
DROP TABLE CONTENIDO CASCADE CONSTRAINTS;
DROP TABLE ROL CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;